
from losses.focal_loss import FocalLoss
from losses.gaussian_nll_loss import GaussianNLLLoss
from losses.laplace_nll_loss import LaplaceNLLLoss
from losses.mixture_nll_loss import MixtureNLLLoss
from losses.mixture_of_gaussian_nll_loss import MixtureOfGaussianNLLLoss
from losses.mixture_of_laplace_nll_loss import MixtureOfLaplaceNLLLoss
from losses.mixture_of_von_mises_nll_loss import MixtureOfVonMisesNLLLoss
from losses.nll_loss import NLLLoss
from losses.soft_target_cross_entropy_loss import SoftTargetCrossEntropyLoss
from losses.von_mises_nll_loss import VonMisesNLLLoss
